### ISSUE TITLE
[c128] Wrong bit bang sounds

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1669] opened 2021-01-13 08:37 UTC
Some bit bang sounds such as `bit_fx(1)` and `bit_fx(7)` are totally wrong on the C128 target. By wrong I mean that they are not just very different from what they sound on other targets (e.g., Spectrum); they are also wrong because are much longer and not useful on any game.

The following code can be used to test `bit_fx(7)` and hear its reproduction
```
#include <sound.h>
#include <stdio.h>
int main(void)
{
    while(1) {
        bit_fx(7);
        getchar();
    }   
    return 0;
}
```
The same code can be adapted to test `bit_fx(1)` which sounds similarly wrong on the C128.

I have attached the wrong sound effect as reproduced by the emulated C128 (Vice):

[2021-01-13 09-35-55.zip](https://github.com/z88dk/z88dk/files/5807391/2021-01-13.09-35-55.zip)

**Comment by zx70** [comment] 2021-01-13 10:43
Are you getting this same behavior also from different environments, such as other emulators and/or a real C128?
The way the bit-banging works on the SID was is not orthodox at all and perhaps the emulators are not expecting it.

**Comment by Fabrizio-Caruso** [comment] 2021-01-13 10:58
I have not used a readl C128 but I have used Z64K and Vice.
Z64K (despite its name) is the most accurate C128 emulator.

Z64K has the same (not identical sounds but somehow similar) problem as Vice.

Some sounds are correctly reproduced by both Vice and Z64K and this may give you a hint for a fix.
For example in the code below, the first two samples are totally wrong and the third one sounds OK.
```
#include <sound.h>
#include <stdio.h>
int main(void)
{
    while(1) {
        bit_fx(7);
        getchar();
        
        bit_fx(1);
        getchar();
        
        bit_fx3(0);
        getchar();
    }   
    return 0;
}
```

**Comment by zx70** [comment] 2021-01-13 11:26
It is a good clue, indeed.
The effects you are claiming not to play correctly are the ones depending on "beeper.asm".
It is caused by the sound initialization (and reset) code being called at every note variation in the fx code loop.

**Comment by zx70** [comment] 2021-01-13 15:36
It should be fixed now.

**Comment by zx70** [comment] 2021-01-13 22:39
Impact was on bit_fx() and bit_fx4() effect groups only.   Now solved.

**Comment by Fabrizio-Caruso** [comment] 2021-01-14 09:55
@zx70 The C128 target has good sounds now but your changes have broken something elsewhere.
On the Spectrum: the sounds will also change the border colors. I fear something really bad could happen on other targets.

**Comment by Fabrizio-Caruso** [comment] 2021-01-14 23:01
@zx70 you can reproduce the problem by using my test program above and compile it for the spectrum target.
The border color is set to purple when the previously wrong sounds are reproduced:
`bit_fx(7),` `bit_fx(1)` while `bit_fx3(0)` resets to its previous color.

**Comment by zx70** [comment] 2021-01-15 07:01
Good news, the past change was consistent with the Spectrum and other targets, the was just an extra small step missing.

**Comment by zx70** [comment] 2021-01-15 07:05
Solved !

**Closed by zx70** 2021-01-15 07:05 UTC
Labels: bug

**Comment by zx70** [comment] 2021-01-15 10:33
Part of the work was useful also to close the issue #1667 related to the bit-banging sound routines messing up the graphics mode.
