### ISSUE TITLE
(g800) The value of getmaxy() is incorrect when using CLIB=g850b

### ISSUE THREAD

**Issue by fu-sen** [z88dk/z88dk#1215] opened 2019-07-01 14:17 UTC
The title is as follows:
[lib/config/g800.cfg](https://github.com/z88dk/z88dk/blob/master/lib/config/g800.cfg)
```
CLIB      g850b   -pragma-need=ansiterminal -D__CONIO_VT100 -pragma-export:ansirows=6  -lg800_clib -lndos
```
There is "-l**g800**_clib".
For example, getmaxy() gets 31(=4*8-1).
It gets disappointing display on some graphics of PC-G850:
[examples/g800/mandel.c](https://github.com/z88dk/z88dk/blob/master/examples/g800/mandel.c)
![スクリーンショット 2019-07-01 08 59 45](https://user-images.githubusercontent.com/5434159/60443216-b4bdc680-9c55-11e9-9fcc-27a8332ed0b4.jpg)

Maybe CLIB=g850 also got the output which is not supposed:
```
CLIB      g850   -pragma-need=ansiterminal -D__CONIO_VT100 -pragma-export:ansirows=8 -pragma-export:ansicolumns=36 -pragma-redirect:ansifont=_font_3x5_850 -pragma-define:ansifont_is_packed=0 -lg850_clib -lndos
```

**Comment by fu-sen** [comment] 2019-07-01 14:39
I examined in detail. As a result, this is 3x5 in the PC-G850 series, so it seems to work correctly:

> Maybe CLIB=g850 also got the output which is not supposed:
> 
> ```
> CLIB      g850   -pragma-need=ansiterminal -D__CONIO_VT100 -pragma-export:ansirows=8 -pragma-export:ansicolumns=36 -pragma-redirect:ansifont=_font_3x5_850 -pragma-define:ansifont_is_packed=0 -lg850_clib -lndos
> ```

On the other hand, there is a problem in that "4 rows text" is included in the corresponding page of wiki.
This should be at "6 rows text":

https://github.com/z88dk/z88dk/wiki/Platform---Sharp-PC#command-line

**Comment by zx70** [comment] 2019-07-03 06:04
I hope I fully understood you report. 
Please revise it and close the issue if the problem is now solved.   I see you opened a parallel issue for the documentation gaps.

**Comment by fu-sen** [comment] 2019-07-03 06:06
Thanks for the quick source improvement. After reflecting on Tomorrow's Nightly, I will confirm it.

**Comment by fu-sen** [comment] 2019-07-04 04:05
I was able to confirm the improvement of this issue.
This is mandel.ihx which I got by making with latest Nightly Build:
![スクリーンショット 2019-07-04 13 01 42](https://user-images.githubusercontent.com/5434159/60639127-30896000-9e5c-11e9-9d9c-ad4eb67f6e59.jpg)
I can close it:

**Comment by zx70** [comment] 2019-07-04 08:46
I'm afraid that this change is not coherent with the text modes, I need to mix the library sources properly.

**Comment by fu-sen** [comment] 2019-07-04 08:55
Oh, I forgot that confirmation. Now that text is lost.
![スクリーンショット 2019-07-04 17 52 46](https://user-images.githubusercontent.com/5434159/60653333-d05ae400-9e84-11e9-8ea1-f5580ad0bfd6.jpg)

**Comment by zx70** [comment] 2019-07-04 09:03
New approach, now I'm attaching only a part of the g850 library (graphics output and keyboard input) to the g800 one.
In this way the 6 rows text mode should be kept but the graphics code will be replaced.

**Comment by fu-sen** [comment] 2019-07-05 04:54
My PC has been updated to Night Build 20190705.
Currently, make is displayed correctly because mandel is built with CLIB = g850:
![スクリーンショット 2019-07-05 13 40 26](https://user-images.githubusercontent.com/5434159/60698782-0acb8c00-9f2c-11e9-82a1-a3fedf3ecca9.jpg)

Problems will occur if CLIB=g850b. Therefore this issue is ongoing:
![スクリーンショット 2019-07-05 13 47 38](https://user-images.githubusercontent.com/5434159/60698796-1323c700-9f2c-11e9-9f44-57abd51dbe02.jpg)

The text display at CLIB=g850b has recovered:
```
#include <stdio.h>

void main() {
  printf(12);

  for (int i=1; i<=6; i++) {
    printf("%c[%u;%uH", 27, i, i);
    printf("test");
  }

  while (!getk());
}
```
 zcc +g800 -create-app -clib=g850b -bn text.ihx text.c
![スクリーンショット 2019-07-05 13 43 05](https://user-images.githubusercontent.com/5434159/60698835-49f9dd00-9f2c-11e9-8ac0-0fc677e71ca7.jpg)

**Comment by zx70** [comment] 2019-07-05 08:27
Sorry for the mess  :construction:
The library linking priority is opposite on the CFG file respect to what happens when when it is user supplied.
You can wait for the next nightly build or simply add also "-lg850b" to your zcc command line.

**Comment by fu-sen** [comment] 2019-07-06 07:06
My PC has been updated to Night Build 20190706.
```
zcc +g800 -create-app -clib=g850b -bn text.ihx text.c
g800 text.ihx 100
```
![スクリーンショット 2019-07-06 15 59 22](https://user-images.githubusercontent.com/5434159/60753013-e7760f00-a007-11e9-8f58-b620a777ab27.jpg)
```
zcc +g800 -lm -create-app -clib=g850b -o mandel.ihx mandel.c
g800 mandel.ihx 100
```
![スクリーンショット 2019-07-06 16 03 52](https://user-images.githubusercontent.com/5434159/60753015-f066e080-a007-11e9-9266-478748ce9ac9.jpg)
it is perfect! I will test a little more but this issue will close soon.

**Closed** 2019-07-10 20:15 UTC
Labels: bug, classiclib

**Comment by zx70** [comment] 2019-07-17 14:29
G850 graphics and console handling are now fairly complete,  a good part of the generic demos should work too

**Comment by fu-sen** [comment] 2019-07-17 14:51
I understood. Thank you for the source improvement for a while.
I will test again several days.

**Comment by fu-sen** [comment] 2019-07-19 15:19
I tested with the latest Nightly Build (20190720)
examples/g800 works fine..
But I confirmed the new problem in the text output.
This may have existed before and will be a separate issue.
