### ISSUE TITLE
sdcc - SIGSEGV with __smallc decorator (was Bug in optimizator)

### ISSUE THREAD

**Issue by zx70** [z88dk/z88dk#1279] opened 2019-09-13 06:31 UTC

**Comment by zx70** [comment] 2019-09-13 06:56
Interestingly, sdcc simply crashes:
Warning: Non-connected liverange found and extended to connected component of the CFG:iTemp29. Please contact sdcc authors with source code to reproduce.
Warning: Non-connected liverange found and extended to connected component of the CFG:iTemp29. Please contact sdcc authors with source code to reproduce.
lzdecode.c:482: error 9: FATAL Compiler Internal Error in file 'gen.c' line number '1679' : Symbol in register, but no register assigned.
Contact Author with source code
Symbol iTemp47 at ic 93.
Caught signal 11: SIGSEGV

**Comment by zx70** [comment] 2019-09-13 14:31
+tag also for zsdcc, since it crashes

**Comment by feilipu** [comment] 2019-09-14 03:34
I've just been experimenting with this, and I can't see the crash with sdcc.
Built with these commands.
```
zcc +cpm -compiler=sdcc -v --list -m -SO3 --c-code-in-asm uuencode.c -o uuencode
zcc +cpm -compiler=sdcc -v --list -m -SO3 --c-code-in-asm uudecode.c -o uudecode
```
The programs (both) run, and open files, but they don't actually work properly, as far as I can see.

**Comment by ped7g** [comment] 2019-09-14 07:46
So if that optimization rule is wrong, then the rule above works how, isn't it wrong too? Or how should I read them?
(the rule above if taken literally as assembly => from `bc = hl, hl = [sp], push bc` to the same with de+hl register pair, i.e. not using `bc` any more).

**Comment by zx70** [comment] 2019-09-14 08:07
Much simpler, bc couldn't be touched, so Dom chose do load the value on the stack.
(Thankyou!)
Those peephole rules couldn't work on a program written natively in asm, they are supposed to know what will never be used by the compiler.
A bit of help comes from the compiler itself by adding comments near the asm instructions.

**Comment by zx70** [comment] 2019-09-14 08:10
He also restricted the rule intervention cases, now it will be active only to push (pointed) values

**Comment by zx70** [comment] 2019-09-16 05:21
Works!

**Comment by feilipu** [comment] 2019-09-16 05:23
@zx70 are you planning to raise the bug with SDCC?
If you haven't already, I'll document and raise.

**Comment by zx70** [comment] 2019-09-16 06:00
Please do  :)
My windows environment is odd and sometimes I get uncommon behaviours

**Comment by zx70** [comment] 2019-09-16 11:30
This new couple of example programs suggested me a new optimization rule.. I'm binding the changes to this issue number.

**Comment by feilipu** [comment] 2019-09-16 11:36
I've raised a [ticket #2932](https://sourceforge.net/p/sdcc/bugs/2932/) on the sdcc bug tracker.

**Comment by suborb** [comment] 2019-09-16 18:31
@zx70 this change is breaking the build (you'll need to regenerate the testsuite result files after checking that they are correct).

It will also break newlib - the crt0 code isn't shared so it will need adding in _DEVELOPMENT/l/sccz80 (I think).

I've disabled the rule for the moment - just remove the obvious line to re-enable it.

**Comment by zx70** [comment] 2019-09-16 19:54
Oops!, sorry !
Thank for having spotted it, I'll check the test files and possibly ask for help later. 
The optimisation looks promising,  lzdecode and clips seem to work correctly and an interesting number of bytes are saved.

**Comment by feilipu** [comment] 2019-09-16 22:13
Reopen with just SDCC label. Pending upstream fix.

**Comment by zx70** [comment] 2019-09-23 09:48
@felipu, I tried to build the programs in a different way (sdcc_iy) and the results are less catastrophic:

bash-3.1$ zcc +cpm -vn -SO3 -clib=sdcc_iy --max-allocs-per-node200000 --opt-code-size lzdecode.c -create-app
Error at file 'fcntl/z80/asm_vopen.asm' line 60: symbol 'asm_target_open_p1' not defined
Error at file 'fcntl/z80/asm_vopen.asm' line 127: symbol 'asm_target_open_p2' not defined
Errors in source file c:/z88dk/lib/config\..\..\\libsrc\_DEVELOPMENT\target\cpm\cpm_crt.asm:
Error at file 'fcntl/z80/asm_vopen.asm' line 60: symbol 'asm_target_open_p1' not defined
Error at file 'fcntl/z80/asm_vopen.asm' line 127: symbol 'asm_target_open_p2' not defined

So the library being linked and the environment matters, I was using the "compiler=sdcc" shortcut, first.

**Comment by suborb** [comment] 2019-09-23 10:03
This seems to match the issues I was experiencing with gbz80 support.

There's something in the classic headers that's causing sdcc to trip over. My hunch is the `__smallc` annotation (or probably more specifically calling a function marked as `__smallc`)

A quick test of `#define __smallc` (so defining it away) and the sdcc segfault goes away.

**Comment by feilipu** [comment] 2019-09-23 10:45
That is interesting. I know @spth prefers to get clean bug reports, so I reproduced the SIGSEGV using a sdcc #11369 (specifically not zsdcc), and used localised versions of the header files (" " rather than < >) to make a stand alone package of files for the bug report.

The outcome is obtained with these commands, using the zip file attached to the [sdcc bug report #2932](https://sourceforge.net/p/sdcc/bugs/2932/).
```
>>:~/Z80/z88dk-ext/os-related/lzdecode$ sdcc -v
SDCC : z80/z180/r2k/r3ka/gbz80/ez80_z80 3.9.3 #11367 (Linux)
published under GNU General Public License (GPL)
>>:~/Z80/z88dk-ext/os-related/lzdecode$ sdcc -D__CPM__ lzdecode.c
Warning: Non-connected liverange found and extended to connected component of the CFG:iTemp29. Please contact sdcc authors with source code to reproduce.
Warning: Non-connected liverange found and extended to connected component of the CFG:iTemp29. Please contact sdcc authors with source code to reproduce.
lzdecode.c:480: error 9: FATAL Compiler Internal Error in file 'gen.c' line number '1687' : Symbol in register, but no register assigned. 
Contact Author with source code
Symbol iTemp47 at ic 93.
Caught signal 11: SIGSEGV
>>:~/Z80/z88dk-ext/os-related/lzdecode$ 
```
So, that should make a small search space in which to identify the problem. Unless `__smallc` is defined through the definition of `__CPM__`, then possibly it is not the problem?

**Comment by zx70** [comment] 2019-09-23 10:58
This thread is getting interesting  :)
I think @suborb is right, the compiler is now surviving.   I loose _feof() for some odd reason, but it gets to the end  !

**Comment by suborb** [comment] 2019-09-23 11:18
@feilipu `__smallc` is always on for the classic headers so that does reduce the search space. 

I've just got back to 9958 and although it succeeds I get these warnings:

```
Warning: Non-connected liverange found and extended to connected component of the CFG:iTemp126. Please contact sdcc authors with source code to reproduce.
Warning: Non-connected liverange found and extended to connected component of the CFG:iTemp126. Please contact sdcc authors with source code to reproduce.
Warning: Non-connected liverange found and extended to connected component of the CFG:iTemp125. Please contact sdcc authors with source code to reproduce.
Warning: Non-connected liverange found and extended to connected component of the CFG:iTemp125. Please contact sdcc authors with source code to reproduce.
Warning: Non-connected liverange found and extended to connected component of the CFG:iTemp29. Please contact sdcc authors with source code to reproduce.
Warning: Non-connected liverange found and extended to connected component of the CFG:iTemp29. Please contact sdcc authors with source code to reproduce.
```

10892 and 11311 fails with the segfault and the liverange warnings. So somewhere between 9958 and 10892 the problem was introduced.

@zx70 Looks like I forgot to add `GLOBAL _feof` in `feof.c`

**Comment by feilipu** [comment] 2019-09-23 11:18
So, I added `#define __smallc` in `sys/complier.h` as below, and the SIGSEGV from sdcc went away.
Some linker warnings appear (also below), but otherwise all good.
See resulting [lzdecode.asm](https://github.com/z88dk/z88dk/files/3641856/lzdecode.asm.txt)

```C
#ifdef __SDCC
#define __LIB__
#define __SAVEFRAME__
#define far
#define __vasmallc
#define __Z88DK_R2L_CALLING_CONVENTION 1
#define __stdc
#define __z88dk_deprecated
#define __z88dk_sdccdecl
#define __smallc                        // < - added to test
#else
#define __vasmallc __smallc
#define __z88dk_deprecated
#endif
```

```
>>:~/Desktop/lzdecode$ sdcc -D__CPM__ lzdecode.c
?ASlink-Warning-Undefined Global '_fputc_callee' referenced by module 'lzdecode'
?ASlink-Warning-Undefined Global '_putchar' referenced by module 'puts'
?ASlink-Warning-Undefined Global '_putchar' referenced by module 'vprintf'
?ASlink-Warning-Undefined Global '_memmove_callee' referenced by module 'lzdecode'
?ASlink-Warning-Undefined Global '_fclose' referenced by module 'lzdecode'
?ASlink-Warning-Undefined Global '_fgetc' referenced by module 'lzdecode'
?ASlink-Warning-Undefined Global '_fopen' referenced by module 'lzdecode'
?ASlink-Warning-Undefined Global '_feof' referenced by module 'lzdecode'
>>:~/Desktop/lzdecode$

**Comment by suborb** [comment] 2019-09-25 12:50
As another qualifier, it needs a char in the prototype for this crash to happen - so I wonder if this was caused by #902

**Comment by feilipu** [comment] 2019-10-08 23:13
@spth prepared [a simplified version of the code](https://sourceforge.net/p/sdcc/bugs/_discuss/thread/19dd020046/7a6b/attachment/lzdecode.c) producing the error, at [sourceforge](https://sourceforge.net/p/sdcc/bugs/2932/#7a6b).

**Comment by spth** [comment] 2019-12-14 10:52
The bug is now fixed in upstream sdcc.

**Comment by feilipu** [comment] 2019-12-14 14:00
@spth are you planning a new stable sdcc. Would be good to close on that (noting you're doing thorough bug squashing at the moment).

**Comment by spth** [comment] 2019-12-14 14:52
I'm aiming for a 4.0.0 release in early 2019 in January or early February. Mostly to get all those improvemnts in the pdk backends into a release.

**Comment by feilipu** [comment] 2019-12-15 11:38
Closed with upstream fix [11494](https://sourceforge.net/p/sdcc/code/11494/)

**Closed by feilipu** 2019-12-15 11:38 UTC
Labels: zsdcc
