### ISSUE TITLE
[clg][KC] clg() produces freezes and random glitches on most KC sub-models

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#683] opened 2018-04-08 14:11 UTC
Hi

I have successfully managed to use the sprite engine with KC! 
I have realized that clg() produces random wrong effects and freezes on most KC sub-models at least when used inside CROSS CHASE (tested with jkcemu):
- on KC/4 -> it breaks the input
- on KC/5 -> on the second execution it locks the computer
Similar problems and/or graphics corruptions are also visibile on these two and other sub-models.

**Comment by zx70** [comment] 2018-04-10 11:42
I can't really explain the impact of clg(), it is a simple ROM call (like the one used all the time by pixeladdress).
In any case I replaced it with a dumb loop clearing the graphics memory (top-left position identified by pixeladdress, then zeroing the next 10240 bytes).
I'm not altering the color attributes to limit the impact, let me know if the tomorrow's build will solve.

**Comment by zx70** [comment] 2018-04-10 17:49
I think I'm getting closer to the root cause, if it is the way I think (ix register affecting the os stability) the last fix won't help much.

**Comment by zx70** [comment] 2018-04-10 18:10
so, googling with the right keywords it is easy to confirm..
https://sourceforge.net/p/sdcc/mailman/message/33036952/

**Comment by suborb** [comment] 2018-04-10 18:13
Aha, lets make kc an ixiy target then  - I presume iy is available?

**Comment by zx70** [comment] 2018-04-11 06:36
My first experiment with the ixiy workaround and the iy library failed, the resulting stability looks worse than with the existing interrupt wrappers protection.   I'm investigating on possible mistakes,

**Comment by Fabrizio-Caruso** [comment] 2018-04-11 07:38
@zx70, some initial tests (only KC 85/5) show that the "fix" has worked by probably avoiding by sheer chance the use of a forbidden register.
The root cause is still there, though, if I understand well.

**Comment by Fabrizio-Caruso** [comment] 2018-04-11 11:09
@zx70 
The new clg() "fixes" all 5 sub-models:
HC 900 *
KC85/2 *
KC85/3 *
KC85/4
KC85/5
The first 3 models (*) have a little glitch: the cursor remains visible on the screen.

**Comment by zx70** [comment] 2018-04-11 11:15
I'm afraid it is just a matter of probability,  in example dstar.c starts correctly clearing the screen perfectly.
Then the game field is drawn and the ball moves under the keyboard control as expected.
On any next clg() the picture gets garbled, probably after the getk() usage random memory areas are corrupted, or some kind of overflow occurs.   In the "CAOS reference" document it is stated:

Restrictions
• do not modify the IX register, this is needed as base pointer to system memory variables by keyboard and cassette loading interrupts
• the only supported interrupt mode is IM2

**Comment by suborb** [comment] 2018-08-25 18:47
I was looking at direct keyboard input for the kc to see if we can bypass the problems with ix.

Unfortunately, the jkcemu emulator actually uses the value of ix when a key is pressed/released so we can't avoid it all unfortunately.

**Comment by feilipu** [comment] 2022-10-18 20:01
Closed by #2092.

**Closed** 2022-10-18 20:01 UTC
Labels: bug, classiclib
