### ISSUE TITLE
sccz80: bug in retrieving unsigned char variable inside logical expression

### ISSUE THREAD

**Issue by aralbrec** [z88dk/z88dk#181] opened 2017-04-20 23:13 UTC
Test code:

```
#define SMS_PNTAddress            0x7800
#define XYtoADDR(x,y)             (SMS_PNTAddress|((unsigned int)(y)<<6)|((unsigned char)(x)<<1))
#define SMS_setNextTileatXY(x,y)  SMS_setAddr(XYtoADDR((x),(y)))

extern void SMS_setTile(unsigned int addr) __z88dk_fastcall;

void writetext(unsigned char *text,unsigned char x, unsigned char y)
{
	SMS_setNextTileatXY (x,y);
}
```

zcc +zx -vn -a -O0 test.c
The bug is marked with asterisks below.

```
._writetext
	ld	hl,2	;const
	add	hl,sp
	ld	l,(hl)
	ld	h,0
	add	hl,hl
	add	hl,hl
	add	hl,hl
	add	hl,hl
	add	hl,hl
	add	hl,hl   ;; hl = y << 6
	ld	a,h
	or	120
	ld	h,a    ;; hl = 0x7800 | y<<6
	push	hl
	ld	hl,6	;const
	add	hl,sp
	ld	h,0  ;************* HL is wrecked before L is loaded
	ld	l,(hl)  ;; hl = x
	ld	h,0
	add	hl,hl  ;; hl = x << 1
	pop	de
	call	l_or
	push	hl
	call	_SMS_setAddr
	pop	bc
	ret
```

**Comment by suborb** [comment] 2017-04-20 23:17
This is a dupe of #26

**Closed by suborb** 2017-04-20 23:17 UTC
Labels: bug
