### ISSUE TITLE
[pps (sprinter)] Keys are wrongly detected

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#792] opened 2018-06-02 09:11 UTC
Keys are wrongly detected.

I am going to provide a simple test.

**Comment by suborb** [comment] 2018-06-04 19:10
@Fabrizio-Caruso have you got any more on this?

We just call the bios so it may have something to do with the emulator - if you run with the debug option on (it's an option in sprint.ini) then I think it logs the scan code to key value mapping.

**Comment by Fabrizio-Caruso** [comment] 2018-06-04 21:00
I am going to isolate the problem to find out how keys are mapped.

**Comment by suborb** [comment] 2018-08-25 23:37
I'm going to close this one since there's a lack of information and I haven't reproduced a problem.

**Closed by suborb** 2018-08-25 23:37 UTC

**Comment by Fabrizio-Caruso** [comment] 2018-08-26 08:33
Sorry, my fault! I will re-test it and let you know more.
