### ISSUE TITLE
Missing .lst file within lst file doesn't error

### ISSUE THREAD

**Issue by suborb** [z88dk/z88dk#795] opened 2018-06-04 16:07 UTC
Issue #790 was caused by a missing a lst file that was included by another lst file. 

I would have expected the build to error, but it appears to have not done so.

**Comment by aralbrec** [comment] 2018-06-04 16:37
If the list file is handed to zcc, the bug will be in zcc as it does its own list file processing.

**Comment by suborb** [comment] 2018-06-04 16:43
This one is within z80asm - the library build for classic uses z80asm directly. Of course zcc might have the same bug!

**Comment by pauloscustodio** [comment] 2018-06-04 22:47
Could not reproduce this in z80asm, both ';' and '#' are detected as comment chars.

**Comment by pauloscustodio** [comment] 2018-07-16 23:44
Found it. Was a consequence of handling globs in list files.

**Closed** 2018-07-16 23:54 UTC
Labels: bug, z80asm
